language: node_js
node_js:
  - "stable"
script:
  - echo "Running tests against $(node -v)..." 
- jest--forceExit --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    